package com.eeeya.fantuan.mapper;

import com.eeeya.fantuan.domain.YfUser;
import com.eeeya.fantuan.domain.YfUserExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface YfUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_user
     *
     * @mbggenerated
     */
    int countByExample(YfUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_user
     *
     * @mbggenerated
     */
    int deleteByExample(YfUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_user
     *
     * @mbggenerated
     */
    int insert(YfUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_user
     *
     * @mbggenerated
     */
    int insertSelective(YfUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_user
     *
     * @mbggenerated
     */
    List<YfUser> selectByExample(YfUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_user
     *
     * @mbggenerated
     */
    YfUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") YfUser record, @Param("example") YfUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") YfUser record, @Param("example") YfUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(YfUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(YfUser record);
}