package com.eeeya.fantuan.domain;

public class YfRestaurantFood {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_restaurant_food.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_restaurant_food.restaurant_id
     *
     * @mbggenerated
     */
    private Long restaurantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_restaurant_food.food_name
     *
     * @mbggenerated
     */
    private String foodName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_restaurant_food.food_price
     *
     * @mbggenerated
     */
    private Integer foodPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_restaurant_food.dianping_url
     *
     * @mbggenerated
     */
    private String dianpingUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_restaurant_food.id
     *
     * @return the value of yf_restaurant_food.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_restaurant_food.id
     *
     * @param id the value for yf_restaurant_food.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_restaurant_food.restaurant_id
     *
     * @return the value of yf_restaurant_food.restaurant_id
     *
     * @mbggenerated
     */
    public Long getRestaurantId() {
        return restaurantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_restaurant_food.restaurant_id
     *
     * @param restaurantId the value for yf_restaurant_food.restaurant_id
     *
     * @mbggenerated
     */
    public void setRestaurantId(Long restaurantId) {
        this.restaurantId = restaurantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_restaurant_food.food_name
     *
     * @return the value of yf_restaurant_food.food_name
     *
     * @mbggenerated
     */
    public String getFoodName() {
        return foodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_restaurant_food.food_name
     *
     * @param foodName the value for yf_restaurant_food.food_name
     *
     * @mbggenerated
     */
    public void setFoodName(String foodName) {
        this.foodName = foodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_restaurant_food.food_price
     *
     * @return the value of yf_restaurant_food.food_price
     *
     * @mbggenerated
     */
    public Integer getFoodPrice() {
        return foodPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_restaurant_food.food_price
     *
     * @param foodPrice the value for yf_restaurant_food.food_price
     *
     * @mbggenerated
     */
    public void setFoodPrice(Integer foodPrice) {
        this.foodPrice = foodPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_restaurant_food.dianping_url
     *
     * @return the value of yf_restaurant_food.dianping_url
     *
     * @mbggenerated
     */
    public String getDianpingUrl() {
        return dianpingUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_restaurant_food.dianping_url
     *
     * @param dianpingUrl the value for yf_restaurant_food.dianping_url
     *
     * @mbggenerated
     */
    public void setDianpingUrl(String dianpingUrl) {
        this.dianpingUrl = dianpingUrl;
    }
}