package com.eeeya.fantuan.domain;

public class YfRestaurant {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_restaurant.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_restaurant.short_name
     *
     * @mbggenerated
     */
    private String shortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_restaurant.full_name
     *
     * @mbggenerated
     */
    private String fullName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_restaurant.max_table
     *
     * @mbggenerated
     */
    private Integer maxTable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_restaurant.restaurant_phone
     *
     * @mbggenerated
     */
    private String restaurantPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_restaurant.restaurant_address
     *
     * @mbggenerated
     */
    private String restaurantAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_restaurant.restaurant_longitude
     *
     * @mbggenerated
     */
    private Double restaurantLongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_restaurant.restaurant_latitude
     *
     * @mbggenerated
     */
    private Double restaurantLatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_restaurant.dianping_url
     *
     * @mbggenerated
     */
    private String dianpingUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_restaurant.id
     *
     * @return the value of yf_restaurant.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_restaurant.id
     *
     * @param id the value for yf_restaurant.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_restaurant.short_name
     *
     * @return the value of yf_restaurant.short_name
     *
     * @mbggenerated
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_restaurant.short_name
     *
     * @param shortName the value for yf_restaurant.short_name
     *
     * @mbggenerated
     */
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_restaurant.full_name
     *
     * @return the value of yf_restaurant.full_name
     *
     * @mbggenerated
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_restaurant.full_name
     *
     * @param fullName the value for yf_restaurant.full_name
     *
     * @mbggenerated
     */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_restaurant.max_table
     *
     * @return the value of yf_restaurant.max_table
     *
     * @mbggenerated
     */
    public Integer getMaxTable() {
        return maxTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_restaurant.max_table
     *
     * @param maxTable the value for yf_restaurant.max_table
     *
     * @mbggenerated
     */
    public void setMaxTable(Integer maxTable) {
        this.maxTable = maxTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_restaurant.restaurant_phone
     *
     * @return the value of yf_restaurant.restaurant_phone
     *
     * @mbggenerated
     */
    public String getRestaurantPhone() {
        return restaurantPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_restaurant.restaurant_phone
     *
     * @param restaurantPhone the value for yf_restaurant.restaurant_phone
     *
     * @mbggenerated
     */
    public void setRestaurantPhone(String restaurantPhone) {
        this.restaurantPhone = restaurantPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_restaurant.restaurant_address
     *
     * @return the value of yf_restaurant.restaurant_address
     *
     * @mbggenerated
     */
    public String getRestaurantAddress() {
        return restaurantAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_restaurant.restaurant_address
     *
     * @param restaurantAddress the value for yf_restaurant.restaurant_address
     *
     * @mbggenerated
     */
    public void setRestaurantAddress(String restaurantAddress) {
        this.restaurantAddress = restaurantAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_restaurant.restaurant_longitude
     *
     * @return the value of yf_restaurant.restaurant_longitude
     *
     * @mbggenerated
     */
    public Double getRestaurantLongitude() {
        return restaurantLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_restaurant.restaurant_longitude
     *
     * @param restaurantLongitude the value for yf_restaurant.restaurant_longitude
     *
     * @mbggenerated
     */
    public void setRestaurantLongitude(Double restaurantLongitude) {
        this.restaurantLongitude = restaurantLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_restaurant.restaurant_latitude
     *
     * @return the value of yf_restaurant.restaurant_latitude
     *
     * @mbggenerated
     */
    public Double getRestaurantLatitude() {
        return restaurantLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_restaurant.restaurant_latitude
     *
     * @param restaurantLatitude the value for yf_restaurant.restaurant_latitude
     *
     * @mbggenerated
     */
    public void setRestaurantLatitude(Double restaurantLatitude) {
        this.restaurantLatitude = restaurantLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_restaurant.dianping_url
     *
     * @return the value of yf_restaurant.dianping_url
     *
     * @mbggenerated
     */
    public String getDianpingUrl() {
        return dianpingUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_restaurant.dianping_url
     *
     * @param dianpingUrl the value for yf_restaurant.dianping_url
     *
     * @mbggenerated
     */
    public void setDianpingUrl(String dianpingUrl) {
        this.dianpingUrl = dianpingUrl;
    }
}