package com.eeeya.fantuan.domain;

public class YfRestaurantImage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_restaurant_image.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_restaurant_image.restaurant_id
     *
     * @mbggenerated
     */
    private Long restaurantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_restaurant_image.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_restaurant_image.id
     *
     * @return the value of yf_restaurant_image.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_restaurant_image.id
     *
     * @param id the value for yf_restaurant_image.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_restaurant_image.restaurant_id
     *
     * @return the value of yf_restaurant_image.restaurant_id
     *
     * @mbggenerated
     */
    public Long getRestaurantId() {
        return restaurantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_restaurant_image.restaurant_id
     *
     * @param restaurantId the value for yf_restaurant_image.restaurant_id
     *
     * @mbggenerated
     */
    public void setRestaurantId(Long restaurantId) {
        this.restaurantId = restaurantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_restaurant_image.url
     *
     * @return the value of yf_restaurant_image.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_restaurant_image.url
     *
     * @param url the value for yf_restaurant_image.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url;
    }
}