package com.eeeya.fantuan.domain;

public class YfTable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_table.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_table.id
     *
     * @return the value of yf_table.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_table.id
     *
     * @param id the value for yf_table.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }
}