package com.eeeya.fantuan.domain;

import java.util.Date;

public class YfUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.telphone
     *
     * @mbggenerated
     */
    private String telphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.constar
     *
     * @mbggenerated
     */
    private String constar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.age
     *
     * @mbggenerated
     */
    private Boolean age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.want
     *
     * @mbggenerated
     */
    private String want;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.job
     *
     * @mbggenerated
     */
    private String job;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.school
     *
     * @mbggenerated
     */
    private String school;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.weibo_name
     *
     * @mbggenerated
     */
    private String weiboName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.weibo_id
     *
     * @mbggenerated
     */
    private String weiboId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.state
     *
     * @mbggenerated
     */
    private Boolean state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.imgid
     *
     * @mbggenerated
     */
    private Boolean imgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.token
     *
     * @mbggenerated
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.lasttime
     *
     * @mbggenerated
     */
    private Date lasttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.breaktime
     *
     * @mbggenerated
     */
    private Integer breaktime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.forbid
     *
     * @mbggenerated
     */
    private Boolean forbid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.longitude
     *
     * @mbggenerated
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.latitude
     *
     * @mbggenerated
     */
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.circle
     *
     * @mbggenerated
     */
    private String circle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.company
     *
     * @mbggenerated
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.salary
     *
     * @mbggenerated
     */
    private String salary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.birth
     *
     * @mbggenerated
     */
    private String birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.birth_datetime
     *
     * @mbggenerated
     */
    private Date birthDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.evaluation
     *
     * @mbggenerated
     */
    private String evaluation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.weight
     *
     * @mbggenerated
     */
    private String weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.height
     *
     * @mbggenerated
     */
    private String height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.like
     *
     * @mbggenerated
     */
    private String like;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.industry
     *
     * @mbggenerated
     */
    private String industry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.industry_id
     *
     * @mbggenerated
     */
    private Integer industryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.hometown
     *
     * @mbggenerated
     */
    private String hometown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.system_info
     *
     * @mbggenerated
     */
    private String systemInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.last_login_time
     *
     * @mbggenerated
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.zombie
     *
     * @mbggenerated
     */
    private Boolean zombie;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.black_state
     *
     * @mbggenerated
     */
    private Boolean blackState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.version
     *
     * @mbggenerated
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.position
     *
     * @mbggenerated
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.neo4j_id
     *
     * @mbggenerated
     */
    private Integer neo4jId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.today_free_mark
     *
     * @mbggenerated
     */
    private Boolean todayFreeMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.today_free_text
     *
     * @mbggenerated
     */
    private String todayFreeText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.mother_marray_mark
     *
     * @mbggenerated
     */
    private Boolean motherMarrayMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.mother_marry_text
     *
     * @mbggenerated
     */
    private String motherMarryText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_user.virtual_mark
     *
     * @mbggenerated
     */
    private Boolean virtualMark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.id
     *
     * @return the value of yf_user.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.id
     *
     * @param id the value for yf_user.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.name
     *
     * @return the value of yf_user.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.name
     *
     * @param name the value for yf_user.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.password
     *
     * @return the value of yf_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.password
     *
     * @param password the value for yf_user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.telphone
     *
     * @return the value of yf_user.telphone
     *
     * @mbggenerated
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.telphone
     *
     * @param telphone the value for yf_user.telphone
     *
     * @mbggenerated
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.constar
     *
     * @return the value of yf_user.constar
     *
     * @mbggenerated
     */
    public String getConstar() {
        return constar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.constar
     *
     * @param constar the value for yf_user.constar
     *
     * @mbggenerated
     */
    public void setConstar(String constar) {
        this.constar = constar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.age
     *
     * @return the value of yf_user.age
     *
     * @mbggenerated
     */
    public Boolean getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.age
     *
     * @param age the value for yf_user.age
     *
     * @mbggenerated
     */
    public void setAge(Boolean age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.sex
     *
     * @return the value of yf_user.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.sex
     *
     * @param sex the value for yf_user.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.want
     *
     * @return the value of yf_user.want
     *
     * @mbggenerated
     */
    public String getWant() {
        return want;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.want
     *
     * @param want the value for yf_user.want
     *
     * @mbggenerated
     */
    public void setWant(String want) {
        this.want = want;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.job
     *
     * @return the value of yf_user.job
     *
     * @mbggenerated
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.job
     *
     * @param job the value for yf_user.job
     *
     * @mbggenerated
     */
    public void setJob(String job) {
        this.job = job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.school
     *
     * @return the value of yf_user.school
     *
     * @mbggenerated
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.school
     *
     * @param school the value for yf_user.school
     *
     * @mbggenerated
     */
    public void setSchool(String school) {
        this.school = school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.weibo_name
     *
     * @return the value of yf_user.weibo_name
     *
     * @mbggenerated
     */
    public String getWeiboName() {
        return weiboName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.weibo_name
     *
     * @param weiboName the value for yf_user.weibo_name
     *
     * @mbggenerated
     */
    public void setWeiboName(String weiboName) {
        this.weiboName = weiboName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.weibo_id
     *
     * @return the value of yf_user.weibo_id
     *
     * @mbggenerated
     */
    public String getWeiboId() {
        return weiboId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.weibo_id
     *
     * @param weiboId the value for yf_user.weibo_id
     *
     * @mbggenerated
     */
    public void setWeiboId(String weiboId) {
        this.weiboId = weiboId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.city
     *
     * @return the value of yf_user.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.city
     *
     * @param city the value for yf_user.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.state
     *
     * @return the value of yf_user.state
     *
     * @mbggenerated
     */
    public Boolean getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.state
     *
     * @param state the value for yf_user.state
     *
     * @mbggenerated
     */
    public void setState(Boolean state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.imgid
     *
     * @return the value of yf_user.imgid
     *
     * @mbggenerated
     */
    public Boolean getImgid() {
        return imgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.imgid
     *
     * @param imgid the value for yf_user.imgid
     *
     * @mbggenerated
     */
    public void setImgid(Boolean imgid) {
        this.imgid = imgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.token
     *
     * @return the value of yf_user.token
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.token
     *
     * @param token the value for yf_user.token
     *
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.lasttime
     *
     * @return the value of yf_user.lasttime
     *
     * @mbggenerated
     */
    public Date getLasttime() {
        return lasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.lasttime
     *
     * @param lasttime the value for yf_user.lasttime
     *
     * @mbggenerated
     */
    public void setLasttime(Date lasttime) {
        this.lasttime = lasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.breaktime
     *
     * @return the value of yf_user.breaktime
     *
     * @mbggenerated
     */
    public Integer getBreaktime() {
        return breaktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.breaktime
     *
     * @param breaktime the value for yf_user.breaktime
     *
     * @mbggenerated
     */
    public void setBreaktime(Integer breaktime) {
        this.breaktime = breaktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.forbid
     *
     * @return the value of yf_user.forbid
     *
     * @mbggenerated
     */
    public Boolean getForbid() {
        return forbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.forbid
     *
     * @param forbid the value for yf_user.forbid
     *
     * @mbggenerated
     */
    public void setForbid(Boolean forbid) {
        this.forbid = forbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.longitude
     *
     * @return the value of yf_user.longitude
     *
     * @mbggenerated
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.longitude
     *
     * @param longitude the value for yf_user.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.latitude
     *
     * @return the value of yf_user.latitude
     *
     * @mbggenerated
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.latitude
     *
     * @param latitude the value for yf_user.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.circle
     *
     * @return the value of yf_user.circle
     *
     * @mbggenerated
     */
    public String getCircle() {
        return circle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.circle
     *
     * @param circle the value for yf_user.circle
     *
     * @mbggenerated
     */
    public void setCircle(String circle) {
        this.circle = circle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.company
     *
     * @return the value of yf_user.company
     *
     * @mbggenerated
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.company
     *
     * @param company the value for yf_user.company
     *
     * @mbggenerated
     */
    public void setCompany(String company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.salary
     *
     * @return the value of yf_user.salary
     *
     * @mbggenerated
     */
    public String getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.salary
     *
     * @param salary the value for yf_user.salary
     *
     * @mbggenerated
     */
    public void setSalary(String salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.birth
     *
     * @return the value of yf_user.birth
     *
     * @mbggenerated
     */
    public String getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.birth
     *
     * @param birth the value for yf_user.birth
     *
     * @mbggenerated
     */
    public void setBirth(String birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.birth_datetime
     *
     * @return the value of yf_user.birth_datetime
     *
     * @mbggenerated
     */
    public Date getBirthDatetime() {
        return birthDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.birth_datetime
     *
     * @param birthDatetime the value for yf_user.birth_datetime
     *
     * @mbggenerated
     */
    public void setBirthDatetime(Date birthDatetime) {
        this.birthDatetime = birthDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.evaluation
     *
     * @return the value of yf_user.evaluation
     *
     * @mbggenerated
     */
    public String getEvaluation() {
        return evaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.evaluation
     *
     * @param evaluation the value for yf_user.evaluation
     *
     * @mbggenerated
     */
    public void setEvaluation(String evaluation) {
        this.evaluation = evaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.weight
     *
     * @return the value of yf_user.weight
     *
     * @mbggenerated
     */
    public String getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.weight
     *
     * @param weight the value for yf_user.weight
     *
     * @mbggenerated
     */
    public void setWeight(String weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.height
     *
     * @return the value of yf_user.height
     *
     * @mbggenerated
     */
    public String getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.height
     *
     * @param height the value for yf_user.height
     *
     * @mbggenerated
     */
    public void setHeight(String height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.like
     *
     * @return the value of yf_user.like
     *
     * @mbggenerated
     */
    public String getLike() {
        return like;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.like
     *
     * @param like the value for yf_user.like
     *
     * @mbggenerated
     */
    public void setLike(String like) {
        this.like = like;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.industry
     *
     * @return the value of yf_user.industry
     *
     * @mbggenerated
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.industry
     *
     * @param industry the value for yf_user.industry
     *
     * @mbggenerated
     */
    public void setIndustry(String industry) {
        this.industry = industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.industry_id
     *
     * @return the value of yf_user.industry_id
     *
     * @mbggenerated
     */
    public Integer getIndustryId() {
        return industryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.industry_id
     *
     * @param industryId the value for yf_user.industry_id
     *
     * @mbggenerated
     */
    public void setIndustryId(Integer industryId) {
        this.industryId = industryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.hometown
     *
     * @return the value of yf_user.hometown
     *
     * @mbggenerated
     */
    public String getHometown() {
        return hometown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.hometown
     *
     * @param hometown the value for yf_user.hometown
     *
     * @mbggenerated
     */
    public void setHometown(String hometown) {
        this.hometown = hometown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.system_info
     *
     * @return the value of yf_user.system_info
     *
     * @mbggenerated
     */
    public String getSystemInfo() {
        return systemInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.system_info
     *
     * @param systemInfo the value for yf_user.system_info
     *
     * @mbggenerated
     */
    public void setSystemInfo(String systemInfo) {
        this.systemInfo = systemInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.last_login_time
     *
     * @return the value of yf_user.last_login_time
     *
     * @mbggenerated
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.last_login_time
     *
     * @param lastLoginTime the value for yf_user.last_login_time
     *
     * @mbggenerated
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.zombie
     *
     * @return the value of yf_user.zombie
     *
     * @mbggenerated
     */
    public Boolean getZombie() {
        return zombie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.zombie
     *
     * @param zombie the value for yf_user.zombie
     *
     * @mbggenerated
     */
    public void setZombie(Boolean zombie) {
        this.zombie = zombie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.black_state
     *
     * @return the value of yf_user.black_state
     *
     * @mbggenerated
     */
    public Boolean getBlackState() {
        return blackState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.black_state
     *
     * @param blackState the value for yf_user.black_state
     *
     * @mbggenerated
     */
    public void setBlackState(Boolean blackState) {
        this.blackState = blackState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.version
     *
     * @return the value of yf_user.version
     *
     * @mbggenerated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.version
     *
     * @param version the value for yf_user.version
     *
     * @mbggenerated
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.position
     *
     * @return the value of yf_user.position
     *
     * @mbggenerated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.position
     *
     * @param position the value for yf_user.position
     *
     * @mbggenerated
     */
    public void setPosition(String position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.neo4j_id
     *
     * @return the value of yf_user.neo4j_id
     *
     * @mbggenerated
     */
    public Integer getNeo4jId() {
        return neo4jId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.neo4j_id
     *
     * @param neo4jId the value for yf_user.neo4j_id
     *
     * @mbggenerated
     */
    public void setNeo4jId(Integer neo4jId) {
        this.neo4jId = neo4jId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.today_free_mark
     *
     * @return the value of yf_user.today_free_mark
     *
     * @mbggenerated
     */
    public Boolean getTodayFreeMark() {
        return todayFreeMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.today_free_mark
     *
     * @param todayFreeMark the value for yf_user.today_free_mark
     *
     * @mbggenerated
     */
    public void setTodayFreeMark(Boolean todayFreeMark) {
        this.todayFreeMark = todayFreeMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.today_free_text
     *
     * @return the value of yf_user.today_free_text
     *
     * @mbggenerated
     */
    public String getTodayFreeText() {
        return todayFreeText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.today_free_text
     *
     * @param todayFreeText the value for yf_user.today_free_text
     *
     * @mbggenerated
     */
    public void setTodayFreeText(String todayFreeText) {
        this.todayFreeText = todayFreeText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.mother_marray_mark
     *
     * @return the value of yf_user.mother_marray_mark
     *
     * @mbggenerated
     */
    public Boolean getMotherMarrayMark() {
        return motherMarrayMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.mother_marray_mark
     *
     * @param motherMarrayMark the value for yf_user.mother_marray_mark
     *
     * @mbggenerated
     */
    public void setMotherMarrayMark(Boolean motherMarrayMark) {
        this.motherMarrayMark = motherMarrayMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.mother_marry_text
     *
     * @return the value of yf_user.mother_marry_text
     *
     * @mbggenerated
     */
    public String getMotherMarryText() {
        return motherMarryText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.mother_marry_text
     *
     * @param motherMarryText the value for yf_user.mother_marry_text
     *
     * @mbggenerated
     */
    public void setMotherMarryText(String motherMarryText) {
        this.motherMarryText = motherMarryText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_user.virtual_mark
     *
     * @return the value of yf_user.virtual_mark
     *
     * @mbggenerated
     */
    public Boolean getVirtualMark() {
        return virtualMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_user.virtual_mark
     *
     * @param virtualMark the value for yf_user.virtual_mark
     *
     * @mbggenerated
     */
    public void setVirtualMark(Boolean virtualMark) {
        this.virtualMark = virtualMark;
    }
}