package com.eeeya.fantuan.server.mapper;

import com.eeeya.fantuan.server.domain.YfImage;
import com.eeeya.fantuan.server.domain.YfImageExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface YfImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_image
     *
     * @mbggenerated
     */
    int countByExample(YfImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_image
     *
     * @mbggenerated
     */
    int deleteByExample(YfImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_image
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_image
     *
     * @mbggenerated
     */
    int insert(YfImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_image
     *
     * @mbggenerated
     */
    int insertSelective(YfImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_image
     *
     * @mbggenerated
     */
    List<YfImage> selectByExample(YfImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_image
     *
     * @mbggenerated
     */
    YfImage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_image
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") YfImage record, @Param("example") YfImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_image
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") YfImage record, @Param("example") YfImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_image
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(YfImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_image
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(YfImage record);
}