package com.eeeya.fantuan.server.mapper;

import com.eeeya.fantuan.server.domain.YfRestaurant;
import com.eeeya.fantuan.server.domain.YfRestaurantExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface YfRestaurantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_restaurant
     *
     * @mbggenerated
     */
    int countByExample(YfRestaurantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_restaurant
     *
     * @mbggenerated
     */
    int deleteByExample(YfRestaurantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_restaurant
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_restaurant
     *
     * @mbggenerated
     */
    int insert(YfRestaurant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_restaurant
     *
     * @mbggenerated
     */
    int insertSelective(YfRestaurant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_restaurant
     *
     * @mbggenerated
     */
    List<YfRestaurant> selectByExample(YfRestaurantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_restaurant
     *
     * @mbggenerated
     */
    YfRestaurant selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_restaurant
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") YfRestaurant record, @Param("example") YfRestaurantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_restaurant
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") YfRestaurant record, @Param("example") YfRestaurantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_restaurant
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(YfRestaurant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_restaurant
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(YfRestaurant record);
}