package com.eeeya.fantuan.server.mapper;

import com.eeeya.fantuan.server.domain.YfRestaurantImage;
import com.eeeya.fantuan.server.domain.YfRestaurantImageExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface YfRestaurantImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_restaurant_image
     *
     * @mbggenerated
     */
    int countByExample(YfRestaurantImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_restaurant_image
     *
     * @mbggenerated
     */
    int deleteByExample(YfRestaurantImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_restaurant_image
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_restaurant_image
     *
     * @mbggenerated
     */
    int insert(YfRestaurantImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_restaurant_image
     *
     * @mbggenerated
     */
    int insertSelective(YfRestaurantImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_restaurant_image
     *
     * @mbggenerated
     */
    List<YfRestaurantImage> selectByExample(YfRestaurantImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_restaurant_image
     *
     * @mbggenerated
     */
    YfRestaurantImage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_restaurant_image
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") YfRestaurantImage record, @Param("example") YfRestaurantImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_restaurant_image
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") YfRestaurantImage record, @Param("example") YfRestaurantImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_restaurant_image
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(YfRestaurantImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_restaurant_image
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(YfRestaurantImage record);
}