package com.eeeya.fantuan.server.mapper;

import com.eeeya.fantuan.server.domain.YfTable;
import com.eeeya.fantuan.server.domain.YfTableExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface YfTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_table
     *
     * @mbggenerated
     */
    int countByExample(YfTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_table
     *
     * @mbggenerated
     */
    int deleteByExample(YfTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_table
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_table
     *
     * @mbggenerated
     */
    int insert(YfTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_table
     *
     * @mbggenerated
     */
    int insertSelective(YfTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_table
     *
     * @mbggenerated
     */
    List<YfTable> selectByExample(YfTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_table
     *
     * @mbggenerated
     */
    YfTable selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_table
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") YfTable record, @Param("example") YfTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_table
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") YfTable record, @Param("example") YfTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_table
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(YfTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_table
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(YfTable record);
}