package com.eeeya.fantuan.server.mapper;

import com.eeeya.fantuan.server.domain.YfTableStart;
import com.eeeya.fantuan.server.domain.YfTableStartExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface YfTableStartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_table_start
     *
     * @mbggenerated
     */
    int countByExample(YfTableStartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_table_start
     *
     * @mbggenerated
     */
    int deleteByExample(YfTableStartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_table_start
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_table_start
     *
     * @mbggenerated
     */
    int insert(YfTableStart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_table_start
     *
     * @mbggenerated
     */
    int insertSelective(YfTableStart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_table_start
     *
     * @mbggenerated
     */
    List<YfTableStart> selectByExample(YfTableStartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_table_start
     *
     * @mbggenerated
     */
    YfTableStart selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_table_start
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") YfTableStart record, @Param("example") YfTableStartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_table_start
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") YfTableStart record, @Param("example") YfTableStartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_table_start
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(YfTableStart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_table_start
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(YfTableStart record);
}