package com.eeeya.fantuan.server.domain;

import java.util.ArrayList;
import java.util.List;

public class YfImageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yf_image
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yf_image
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yf_image
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yf_image
     *
     * @mbggenerated
     */
    protected int offset = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yf_image
     *
     * @mbggenerated
     */
    protected int rows = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_image
     *
     * @mbggenerated
     */
    public YfImageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_image
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_image
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_image
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_image
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_image
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_image
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_image
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_image
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_image
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_image
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_image
     *
     * @mbggenerated
     */
    public void setOffset(int offset) {
        this.offset=offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_image
     *
     * @mbggenerated
     */
    public int getOffset() {
        return offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_image
     *
     * @mbggenerated
     */
    public void setRows(int rows) {
        this.rows=rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_image
     *
     * @mbggenerated
     */
    public int getRows() {
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yf_image
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userid is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userid is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Long value) {
            addCriterion("userid =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Long value) {
            addCriterion("userid <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Long value) {
            addCriterion("userid >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Long value) {
            addCriterion("userid >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Long value) {
            addCriterion("userid <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Long value) {
            addCriterion("userid <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Long> values) {
            addCriterion("userid in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Long> values) {
            addCriterion("userid not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Long value1, Long value2) {
            addCriterion("userid between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Long value1, Long value2) {
            addCriterion("userid not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andImgsrcIsNull() {
            addCriterion("imgsrc is null");
            return (Criteria) this;
        }

        public Criteria andImgsrcIsNotNull() {
            addCriterion("imgsrc is not null");
            return (Criteria) this;
        }

        public Criteria andImgsrcEqualTo(String value) {
            addCriterion("imgsrc =", value, "imgsrc");
            return (Criteria) this;
        }

        public Criteria andImgsrcNotEqualTo(String value) {
            addCriterion("imgsrc <>", value, "imgsrc");
            return (Criteria) this;
        }

        public Criteria andImgsrcGreaterThan(String value) {
            addCriterion("imgsrc >", value, "imgsrc");
            return (Criteria) this;
        }

        public Criteria andImgsrcGreaterThanOrEqualTo(String value) {
            addCriterion("imgsrc >=", value, "imgsrc");
            return (Criteria) this;
        }

        public Criteria andImgsrcLessThan(String value) {
            addCriterion("imgsrc <", value, "imgsrc");
            return (Criteria) this;
        }

        public Criteria andImgsrcLessThanOrEqualTo(String value) {
            addCriterion("imgsrc <=", value, "imgsrc");
            return (Criteria) this;
        }

        public Criteria andImgsrcLike(String value) {
            addCriterion("imgsrc like", value, "imgsrc");
            return (Criteria) this;
        }

        public Criteria andImgsrcNotLike(String value) {
            addCriterion("imgsrc not like", value, "imgsrc");
            return (Criteria) this;
        }

        public Criteria andImgsrcIn(List<String> values) {
            addCriterion("imgsrc in", values, "imgsrc");
            return (Criteria) this;
        }

        public Criteria andImgsrcNotIn(List<String> values) {
            addCriterion("imgsrc not in", values, "imgsrc");
            return (Criteria) this;
        }

        public Criteria andImgsrcBetween(String value1, String value2) {
            addCriterion("imgsrc between", value1, value2, "imgsrc");
            return (Criteria) this;
        }

        public Criteria andImgsrcNotBetween(String value1, String value2) {
            addCriterion("imgsrc not between", value1, value2, "imgsrc");
            return (Criteria) this;
        }

        public Criteria andDefaultMarkIsNull() {
            addCriterion("default_mark is null");
            return (Criteria) this;
        }

        public Criteria andDefaultMarkIsNotNull() {
            addCriterion("default_mark is not null");
            return (Criteria) this;
        }

        public Criteria andDefaultMarkEqualTo(Boolean value) {
            addCriterion("default_mark =", value, "defaultMark");
            return (Criteria) this;
        }

        public Criteria andDefaultMarkNotEqualTo(Boolean value) {
            addCriterion("default_mark <>", value, "defaultMark");
            return (Criteria) this;
        }

        public Criteria andDefaultMarkGreaterThan(Boolean value) {
            addCriterion("default_mark >", value, "defaultMark");
            return (Criteria) this;
        }

        public Criteria andDefaultMarkGreaterThanOrEqualTo(Boolean value) {
            addCriterion("default_mark >=", value, "defaultMark");
            return (Criteria) this;
        }

        public Criteria andDefaultMarkLessThan(Boolean value) {
            addCriterion("default_mark <", value, "defaultMark");
            return (Criteria) this;
        }

        public Criteria andDefaultMarkLessThanOrEqualTo(Boolean value) {
            addCriterion("default_mark <=", value, "defaultMark");
            return (Criteria) this;
        }

        public Criteria andDefaultMarkIn(List<Boolean> values) {
            addCriterion("default_mark in", values, "defaultMark");
            return (Criteria) this;
        }

        public Criteria andDefaultMarkNotIn(List<Boolean> values) {
            addCriterion("default_mark not in", values, "defaultMark");
            return (Criteria) this;
        }

        public Criteria andDefaultMarkBetween(Boolean value1, Boolean value2) {
            addCriterion("default_mark between", value1, value2, "defaultMark");
            return (Criteria) this;
        }

        public Criteria andDefaultMarkNotBetween(Boolean value1, Boolean value2) {
            addCriterion("default_mark not between", value1, value2, "defaultMark");
            return (Criteria) this;
        }

        public Criteria andMarkIsNull() {
            addCriterion("mark is null");
            return (Criteria) this;
        }

        public Criteria andMarkIsNotNull() {
            addCriterion("mark is not null");
            return (Criteria) this;
        }

        public Criteria andMarkEqualTo(Byte value) {
            addCriterion("mark =", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkNotEqualTo(Byte value) {
            addCriterion("mark <>", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkGreaterThan(Byte value) {
            addCriterion("mark >", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkGreaterThanOrEqualTo(Byte value) {
            addCriterion("mark >=", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkLessThan(Byte value) {
            addCriterion("mark <", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkLessThanOrEqualTo(Byte value) {
            addCriterion("mark <=", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkIn(List<Byte> values) {
            addCriterion("mark in", values, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkNotIn(List<Byte> values) {
            addCriterion("mark not in", values, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkBetween(Byte value1, Byte value2) {
            addCriterion("mark between", value1, value2, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkNotBetween(Byte value1, Byte value2) {
            addCriterion("mark not between", value1, value2, "mark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yf_image
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yf_image
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}