package com.eeeya.fantuan.server.domain;

public class YfImage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_image.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_image.userid
     *
     * @mbggenerated
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_image.imgsrc
     *
     * @mbggenerated
     */
    private String imgsrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_image.default_mark
     *
     * @mbggenerated
     */
    private Boolean defaultMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_image.mark
     *
     * @mbggenerated
     */
    private Byte mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_image.id
     *
     * @return the value of yf_image.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_image.id
     *
     * @param id the value for yf_image.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_image.userid
     *
     * @return the value of yf_image.userid
     *
     * @mbggenerated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_image.userid
     *
     * @param userid the value for yf_image.userid
     *
     * @mbggenerated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_image.imgsrc
     *
     * @return the value of yf_image.imgsrc
     *
     * @mbggenerated
     */
    public String getImgsrc() {
        return imgsrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_image.imgsrc
     *
     * @param imgsrc the value for yf_image.imgsrc
     *
     * @mbggenerated
     */
    public void setImgsrc(String imgsrc) {
        this.imgsrc = imgsrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_image.default_mark
     *
     * @return the value of yf_image.default_mark
     *
     * @mbggenerated
     */
    public Boolean getDefaultMark() {
        return defaultMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_image.default_mark
     *
     * @param defaultMark the value for yf_image.default_mark
     *
     * @mbggenerated
     */
    public void setDefaultMark(Boolean defaultMark) {
        this.defaultMark = defaultMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_image.mark
     *
     * @return the value of yf_image.mark
     *
     * @mbggenerated
     */
    public Byte getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_image.mark
     *
     * @param mark the value for yf_image.mark
     *
     * @mbggenerated
     */
    public void setMark(Byte mark) {
        this.mark = mark;
    }
}