package com.eeeya.fantuan.server.domain;

import java.util.ArrayList;
import java.util.List;

public class YfRestaurantExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yf_restaurant
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yf_restaurant
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yf_restaurant
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yf_restaurant
     *
     * @mbggenerated
     */
    protected int offset = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yf_restaurant
     *
     * @mbggenerated
     */
    protected int rows = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_restaurant
     *
     * @mbggenerated
     */
    public YfRestaurantExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_restaurant
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_restaurant
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_restaurant
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_restaurant
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_restaurant
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_restaurant
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_restaurant
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_restaurant
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_restaurant
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_restaurant
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_restaurant
     *
     * @mbggenerated
     */
    public void setOffset(int offset) {
        this.offset=offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_restaurant
     *
     * @mbggenerated
     */
    public int getOffset() {
        return offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_restaurant
     *
     * @mbggenerated
     */
    public void setRows(int rows) {
        this.rows=rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yf_restaurant
     *
     * @mbggenerated
     */
    public int getRows() {
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yf_restaurant
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andShortNameIsNull() {
            addCriterion("short_name is null");
            return (Criteria) this;
        }

        public Criteria andShortNameIsNotNull() {
            addCriterion("short_name is not null");
            return (Criteria) this;
        }

        public Criteria andShortNameEqualTo(String value) {
            addCriterion("short_name =", value, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameNotEqualTo(String value) {
            addCriterion("short_name <>", value, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameGreaterThan(String value) {
            addCriterion("short_name >", value, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameGreaterThanOrEqualTo(String value) {
            addCriterion("short_name >=", value, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameLessThan(String value) {
            addCriterion("short_name <", value, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameLessThanOrEqualTo(String value) {
            addCriterion("short_name <=", value, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameLike(String value) {
            addCriterion("short_name like", value, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameNotLike(String value) {
            addCriterion("short_name not like", value, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameIn(List<String> values) {
            addCriterion("short_name in", values, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameNotIn(List<String> values) {
            addCriterion("short_name not in", values, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameBetween(String value1, String value2) {
            addCriterion("short_name between", value1, value2, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameNotBetween(String value1, String value2) {
            addCriterion("short_name not between", value1, value2, "shortName");
            return (Criteria) this;
        }

        public Criteria andFullNameIsNull() {
            addCriterion("full_name is null");
            return (Criteria) this;
        }

        public Criteria andFullNameIsNotNull() {
            addCriterion("full_name is not null");
            return (Criteria) this;
        }

        public Criteria andFullNameEqualTo(String value) {
            addCriterion("full_name =", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameNotEqualTo(String value) {
            addCriterion("full_name <>", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameGreaterThan(String value) {
            addCriterion("full_name >", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameGreaterThanOrEqualTo(String value) {
            addCriterion("full_name >=", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameLessThan(String value) {
            addCriterion("full_name <", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameLessThanOrEqualTo(String value) {
            addCriterion("full_name <=", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameLike(String value) {
            addCriterion("full_name like", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameNotLike(String value) {
            addCriterion("full_name not like", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameIn(List<String> values) {
            addCriterion("full_name in", values, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameNotIn(List<String> values) {
            addCriterion("full_name not in", values, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameBetween(String value1, String value2) {
            addCriterion("full_name between", value1, value2, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameNotBetween(String value1, String value2) {
            addCriterion("full_name not between", value1, value2, "fullName");
            return (Criteria) this;
        }

        public Criteria andMaxTableIsNull() {
            addCriterion("max_table is null");
            return (Criteria) this;
        }

        public Criteria andMaxTableIsNotNull() {
            addCriterion("max_table is not null");
            return (Criteria) this;
        }

        public Criteria andMaxTableEqualTo(Integer value) {
            addCriterion("max_table =", value, "maxTable");
            return (Criteria) this;
        }

        public Criteria andMaxTableNotEqualTo(Integer value) {
            addCriterion("max_table <>", value, "maxTable");
            return (Criteria) this;
        }

        public Criteria andMaxTableGreaterThan(Integer value) {
            addCriterion("max_table >", value, "maxTable");
            return (Criteria) this;
        }

        public Criteria andMaxTableGreaterThanOrEqualTo(Integer value) {
            addCriterion("max_table >=", value, "maxTable");
            return (Criteria) this;
        }

        public Criteria andMaxTableLessThan(Integer value) {
            addCriterion("max_table <", value, "maxTable");
            return (Criteria) this;
        }

        public Criteria andMaxTableLessThanOrEqualTo(Integer value) {
            addCriterion("max_table <=", value, "maxTable");
            return (Criteria) this;
        }

        public Criteria andMaxTableIn(List<Integer> values) {
            addCriterion("max_table in", values, "maxTable");
            return (Criteria) this;
        }

        public Criteria andMaxTableNotIn(List<Integer> values) {
            addCriterion("max_table not in", values, "maxTable");
            return (Criteria) this;
        }

        public Criteria andMaxTableBetween(Integer value1, Integer value2) {
            addCriterion("max_table between", value1, value2, "maxTable");
            return (Criteria) this;
        }

        public Criteria andMaxTableNotBetween(Integer value1, Integer value2) {
            addCriterion("max_table not between", value1, value2, "maxTable");
            return (Criteria) this;
        }

        public Criteria andRestaurantPhoneIsNull() {
            addCriterion("restaurant_phone is null");
            return (Criteria) this;
        }

        public Criteria andRestaurantPhoneIsNotNull() {
            addCriterion("restaurant_phone is not null");
            return (Criteria) this;
        }

        public Criteria andRestaurantPhoneEqualTo(String value) {
            addCriterion("restaurant_phone =", value, "restaurantPhone");
            return (Criteria) this;
        }

        public Criteria andRestaurantPhoneNotEqualTo(String value) {
            addCriterion("restaurant_phone <>", value, "restaurantPhone");
            return (Criteria) this;
        }

        public Criteria andRestaurantPhoneGreaterThan(String value) {
            addCriterion("restaurant_phone >", value, "restaurantPhone");
            return (Criteria) this;
        }

        public Criteria andRestaurantPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("restaurant_phone >=", value, "restaurantPhone");
            return (Criteria) this;
        }

        public Criteria andRestaurantPhoneLessThan(String value) {
            addCriterion("restaurant_phone <", value, "restaurantPhone");
            return (Criteria) this;
        }

        public Criteria andRestaurantPhoneLessThanOrEqualTo(String value) {
            addCriterion("restaurant_phone <=", value, "restaurantPhone");
            return (Criteria) this;
        }

        public Criteria andRestaurantPhoneLike(String value) {
            addCriterion("restaurant_phone like", value, "restaurantPhone");
            return (Criteria) this;
        }

        public Criteria andRestaurantPhoneNotLike(String value) {
            addCriterion("restaurant_phone not like", value, "restaurantPhone");
            return (Criteria) this;
        }

        public Criteria andRestaurantPhoneIn(List<String> values) {
            addCriterion("restaurant_phone in", values, "restaurantPhone");
            return (Criteria) this;
        }

        public Criteria andRestaurantPhoneNotIn(List<String> values) {
            addCriterion("restaurant_phone not in", values, "restaurantPhone");
            return (Criteria) this;
        }

        public Criteria andRestaurantPhoneBetween(String value1, String value2) {
            addCriterion("restaurant_phone between", value1, value2, "restaurantPhone");
            return (Criteria) this;
        }

        public Criteria andRestaurantPhoneNotBetween(String value1, String value2) {
            addCriterion("restaurant_phone not between", value1, value2, "restaurantPhone");
            return (Criteria) this;
        }

        public Criteria andRestaurantAddressIsNull() {
            addCriterion("restaurant_address is null");
            return (Criteria) this;
        }

        public Criteria andRestaurantAddressIsNotNull() {
            addCriterion("restaurant_address is not null");
            return (Criteria) this;
        }

        public Criteria andRestaurantAddressEqualTo(String value) {
            addCriterion("restaurant_address =", value, "restaurantAddress");
            return (Criteria) this;
        }

        public Criteria andRestaurantAddressNotEqualTo(String value) {
            addCriterion("restaurant_address <>", value, "restaurantAddress");
            return (Criteria) this;
        }

        public Criteria andRestaurantAddressGreaterThan(String value) {
            addCriterion("restaurant_address >", value, "restaurantAddress");
            return (Criteria) this;
        }

        public Criteria andRestaurantAddressGreaterThanOrEqualTo(String value) {
            addCriterion("restaurant_address >=", value, "restaurantAddress");
            return (Criteria) this;
        }

        public Criteria andRestaurantAddressLessThan(String value) {
            addCriterion("restaurant_address <", value, "restaurantAddress");
            return (Criteria) this;
        }

        public Criteria andRestaurantAddressLessThanOrEqualTo(String value) {
            addCriterion("restaurant_address <=", value, "restaurantAddress");
            return (Criteria) this;
        }

        public Criteria andRestaurantAddressLike(String value) {
            addCriterion("restaurant_address like", value, "restaurantAddress");
            return (Criteria) this;
        }

        public Criteria andRestaurantAddressNotLike(String value) {
            addCriterion("restaurant_address not like", value, "restaurantAddress");
            return (Criteria) this;
        }

        public Criteria andRestaurantAddressIn(List<String> values) {
            addCriterion("restaurant_address in", values, "restaurantAddress");
            return (Criteria) this;
        }

        public Criteria andRestaurantAddressNotIn(List<String> values) {
            addCriterion("restaurant_address not in", values, "restaurantAddress");
            return (Criteria) this;
        }

        public Criteria andRestaurantAddressBetween(String value1, String value2) {
            addCriterion("restaurant_address between", value1, value2, "restaurantAddress");
            return (Criteria) this;
        }

        public Criteria andRestaurantAddressNotBetween(String value1, String value2) {
            addCriterion("restaurant_address not between", value1, value2, "restaurantAddress");
            return (Criteria) this;
        }

        public Criteria andRestaurantLongitudeIsNull() {
            addCriterion("restaurant_longitude is null");
            return (Criteria) this;
        }

        public Criteria andRestaurantLongitudeIsNotNull() {
            addCriterion("restaurant_longitude is not null");
            return (Criteria) this;
        }

        public Criteria andRestaurantLongitudeEqualTo(Double value) {
            addCriterion("restaurant_longitude =", value, "restaurantLongitude");
            return (Criteria) this;
        }

        public Criteria andRestaurantLongitudeNotEqualTo(Double value) {
            addCriterion("restaurant_longitude <>", value, "restaurantLongitude");
            return (Criteria) this;
        }

        public Criteria andRestaurantLongitudeGreaterThan(Double value) {
            addCriterion("restaurant_longitude >", value, "restaurantLongitude");
            return (Criteria) this;
        }

        public Criteria andRestaurantLongitudeGreaterThanOrEqualTo(Double value) {
            addCriterion("restaurant_longitude >=", value, "restaurantLongitude");
            return (Criteria) this;
        }

        public Criteria andRestaurantLongitudeLessThan(Double value) {
            addCriterion("restaurant_longitude <", value, "restaurantLongitude");
            return (Criteria) this;
        }

        public Criteria andRestaurantLongitudeLessThanOrEqualTo(Double value) {
            addCriterion("restaurant_longitude <=", value, "restaurantLongitude");
            return (Criteria) this;
        }

        public Criteria andRestaurantLongitudeIn(List<Double> values) {
            addCriterion("restaurant_longitude in", values, "restaurantLongitude");
            return (Criteria) this;
        }

        public Criteria andRestaurantLongitudeNotIn(List<Double> values) {
            addCriterion("restaurant_longitude not in", values, "restaurantLongitude");
            return (Criteria) this;
        }

        public Criteria andRestaurantLongitudeBetween(Double value1, Double value2) {
            addCriterion("restaurant_longitude between", value1, value2, "restaurantLongitude");
            return (Criteria) this;
        }

        public Criteria andRestaurantLongitudeNotBetween(Double value1, Double value2) {
            addCriterion("restaurant_longitude not between", value1, value2, "restaurantLongitude");
            return (Criteria) this;
        }

        public Criteria andRestaurantLatitudeIsNull() {
            addCriterion("restaurant_latitude is null");
            return (Criteria) this;
        }

        public Criteria andRestaurantLatitudeIsNotNull() {
            addCriterion("restaurant_latitude is not null");
            return (Criteria) this;
        }

        public Criteria andRestaurantLatitudeEqualTo(Double value) {
            addCriterion("restaurant_latitude =", value, "restaurantLatitude");
            return (Criteria) this;
        }

        public Criteria andRestaurantLatitudeNotEqualTo(Double value) {
            addCriterion("restaurant_latitude <>", value, "restaurantLatitude");
            return (Criteria) this;
        }

        public Criteria andRestaurantLatitudeGreaterThan(Double value) {
            addCriterion("restaurant_latitude >", value, "restaurantLatitude");
            return (Criteria) this;
        }

        public Criteria andRestaurantLatitudeGreaterThanOrEqualTo(Double value) {
            addCriterion("restaurant_latitude >=", value, "restaurantLatitude");
            return (Criteria) this;
        }

        public Criteria andRestaurantLatitudeLessThan(Double value) {
            addCriterion("restaurant_latitude <", value, "restaurantLatitude");
            return (Criteria) this;
        }

        public Criteria andRestaurantLatitudeLessThanOrEqualTo(Double value) {
            addCriterion("restaurant_latitude <=", value, "restaurantLatitude");
            return (Criteria) this;
        }

        public Criteria andRestaurantLatitudeIn(List<Double> values) {
            addCriterion("restaurant_latitude in", values, "restaurantLatitude");
            return (Criteria) this;
        }

        public Criteria andRestaurantLatitudeNotIn(List<Double> values) {
            addCriterion("restaurant_latitude not in", values, "restaurantLatitude");
            return (Criteria) this;
        }

        public Criteria andRestaurantLatitudeBetween(Double value1, Double value2) {
            addCriterion("restaurant_latitude between", value1, value2, "restaurantLatitude");
            return (Criteria) this;
        }

        public Criteria andRestaurantLatitudeNotBetween(Double value1, Double value2) {
            addCriterion("restaurant_latitude not between", value1, value2, "restaurantLatitude");
            return (Criteria) this;
        }

        public Criteria andDianpingUrlIsNull() {
            addCriterion("dianping_url is null");
            return (Criteria) this;
        }

        public Criteria andDianpingUrlIsNotNull() {
            addCriterion("dianping_url is not null");
            return (Criteria) this;
        }

        public Criteria andDianpingUrlEqualTo(String value) {
            addCriterion("dianping_url =", value, "dianpingUrl");
            return (Criteria) this;
        }

        public Criteria andDianpingUrlNotEqualTo(String value) {
            addCriterion("dianping_url <>", value, "dianpingUrl");
            return (Criteria) this;
        }

        public Criteria andDianpingUrlGreaterThan(String value) {
            addCriterion("dianping_url >", value, "dianpingUrl");
            return (Criteria) this;
        }

        public Criteria andDianpingUrlGreaterThanOrEqualTo(String value) {
            addCriterion("dianping_url >=", value, "dianpingUrl");
            return (Criteria) this;
        }

        public Criteria andDianpingUrlLessThan(String value) {
            addCriterion("dianping_url <", value, "dianpingUrl");
            return (Criteria) this;
        }

        public Criteria andDianpingUrlLessThanOrEqualTo(String value) {
            addCriterion("dianping_url <=", value, "dianpingUrl");
            return (Criteria) this;
        }

        public Criteria andDianpingUrlLike(String value) {
            addCriterion("dianping_url like", value, "dianpingUrl");
            return (Criteria) this;
        }

        public Criteria andDianpingUrlNotLike(String value) {
            addCriterion("dianping_url not like", value, "dianpingUrl");
            return (Criteria) this;
        }

        public Criteria andDianpingUrlIn(List<String> values) {
            addCriterion("dianping_url in", values, "dianpingUrl");
            return (Criteria) this;
        }

        public Criteria andDianpingUrlNotIn(List<String> values) {
            addCriterion("dianping_url not in", values, "dianpingUrl");
            return (Criteria) this;
        }

        public Criteria andDianpingUrlBetween(String value1, String value2) {
            addCriterion("dianping_url between", value1, value2, "dianpingUrl");
            return (Criteria) this;
        }

        public Criteria andDianpingUrlNotBetween(String value1, String value2) {
            addCriterion("dianping_url not between", value1, value2, "dianpingUrl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yf_restaurant
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yf_restaurant
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}