package com.eeeya.fantuan.server.domain;

import java.util.Date;

public class YfTable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_table.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_table.meal_time
     *
     * @mbggenerated
     */
    private Date mealTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_table.meal_type
     *
     * @mbggenerated
     */
    private Byte mealType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_table.table_type
     *
     * @mbggenerated
     */
    private Byte tableType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_table.pay_type
     *
     * @mbggenerated
     */
    private Byte payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_table.restaurant_Id
     *
     * @mbggenerated
     */
    private Long restaurantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_table.talk_group_id
     *
     * @mbggenerated
     */
    private Integer talkGroupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_table.id
     *
     * @return the value of yf_table.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_table.id
     *
     * @param id the value for yf_table.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_table.meal_time
     *
     * @return the value of yf_table.meal_time
     *
     * @mbggenerated
     */
    public Date getMealTime() {
        return mealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_table.meal_time
     *
     * @param mealTime the value for yf_table.meal_time
     *
     * @mbggenerated
     */
    public void setMealTime(Date mealTime) {
        this.mealTime = mealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_table.meal_type
     *
     * @return the value of yf_table.meal_type
     *
     * @mbggenerated
     */
    public Byte getMealType() {
        return mealType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_table.meal_type
     *
     * @param mealType the value for yf_table.meal_type
     *
     * @mbggenerated
     */
    public void setMealType(Byte mealType) {
        this.mealType = mealType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_table.table_type
     *
     * @return the value of yf_table.table_type
     *
     * @mbggenerated
     */
    public Byte getTableType() {
        return tableType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_table.table_type
     *
     * @param tableType the value for yf_table.table_type
     *
     * @mbggenerated
     */
    public void setTableType(Byte tableType) {
        this.tableType = tableType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_table.pay_type
     *
     * @return the value of yf_table.pay_type
     *
     * @mbggenerated
     */
    public Byte getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_table.pay_type
     *
     * @param payType the value for yf_table.pay_type
     *
     * @mbggenerated
     */
    public void setPayType(Byte payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_table.restaurant_Id
     *
     * @return the value of yf_table.restaurant_Id
     *
     * @mbggenerated
     */
    public Long getRestaurantId() {
        return restaurantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_table.restaurant_Id
     *
     * @param restaurantId the value for yf_table.restaurant_Id
     *
     * @mbggenerated
     */
    public void setRestaurantId(Long restaurantId) {
        this.restaurantId = restaurantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_table.talk_group_id
     *
     * @return the value of yf_table.talk_group_id
     *
     * @mbggenerated
     */
    public Integer getTalkGroupId() {
        return talkGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_table.talk_group_id
     *
     * @param talkGroupId the value for yf_table.talk_group_id
     *
     * @mbggenerated
     */
    public void setTalkGroupId(Integer talkGroupId) {
        this.talkGroupId = talkGroupId;
    }
}