package com.eeeya.fantuan.server.domain;

import java.util.Date;

public class YfTableJoin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_table_join.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_table_join.join_time
     *
     * @mbggenerated
     */
    private Date joinTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_table_join.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yf_table_join.table_id
     *
     * @mbggenerated
     */
    private Long tableId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_table_join.id
     *
     * @return the value of yf_table_join.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_table_join.id
     *
     * @param id the value for yf_table_join.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_table_join.join_time
     *
     * @return the value of yf_table_join.join_time
     *
     * @mbggenerated
     */
    public Date getJoinTime() {
        return joinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_table_join.join_time
     *
     * @param joinTime the value for yf_table_join.join_time
     *
     * @mbggenerated
     */
    public void setJoinTime(Date joinTime) {
        this.joinTime = joinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_table_join.user_id
     *
     * @return the value of yf_table_join.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_table_join.user_id
     *
     * @param userId the value for yf_table_join.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yf_table_join.table_id
     *
     * @return the value of yf_table_join.table_id
     *
     * @mbggenerated
     */
    public Long getTableId() {
        return tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yf_table_join.table_id
     *
     * @param tableId the value for yf_table_join.table_id
     *
     * @mbggenerated
     */
    public void setTableId(Long tableId) {
        this.tableId = tableId;
    }
}